from setuptools import setup, find_packages

with open("README.md", "r") as fh:
    long_description = fh.read()

setup(
    name="vimms",
    version="1.1.0",
    author="Joe Wandy, Vinny Davies, Justin J.J. van der Hooft, Stefan Weidt, Ronan Daly, Simon Rogers",
    author_email="Simon.Rogers@glasgow.ac.uk",
    description="ViMMS is an LC-MS/MS simulator.",
    long_description="ViMMS is a modular LC-MS/MS simulator framework for metabolomics that allows for real-time scan-level control of the MS2 acquisition process in-silico. ViMMS allows users to simulate and test different fragmentation strategies and obtain fragmentation files in .mzML format as output from the simulation (the entire state of the simulator can also be saved for inspection later).",
    long_description_content_type="text/markdown",
    url="https://github.com/sdrogers/vimms",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.6",
    packages=find_packages(),
    install_requires=[
        "async-generator==1.10",
        "atomicwrites==1.4.0; sys_platform == 'win32'",
        "attrs==19.3.0",
        "backcall==0.2.0",
        "bleach==3.1.5",
        "certifi==2020.6.20",
        "cffi==1.14.1; os_name == 'nt' and implementation_name != 'pypy'",
        "chardet==3.0.4",
        "colorama==0.4.3; sys_platform == 'win32'",
        "cycler==0.10.0",
        "decorator==4.4.2",
        "defusedxml==0.6.0",
        "entrypoints==0.3",
        "events==0.3",
        "idna==2.10",
        "importlib-metadata==1.7.0; python_version < '3.8'",
        "iniconfig==1.0.0",
        "ipykernel==5.3.4",
        "ipyparallel==6.3.0",
        "ipython==7.16.1; python_version >= '3.3'",
        "ipython-genutils==0.2.0",
        "ipywidgets==7.5.1",
        "jedi==0.17.2",
        "jinja2==2.11.2",
        "joblib==0.16.0",
        "json5==0.9.5",
        "jsonpickle==1.4.1",
        "jsonschema==3.2.0",
        "jupyter==1.0.0",
        "jupyter-client==6.1.6",
        "jupyter-console==6.1.0",
        "jupyter-core==4.6.3",
        "jupyterlab==2.2.2",
        "jupyterlab-server==1.2.0",
        "kiwisolver==1.2.0",
        "loguru==0.5.1",
        "lxml==4.5.2",
        "markupsafe==1.1.1",
        "mass-spec-utils==0.0.6",
        "matplotlib==3.3.0",
        "mistune==0.8.4",
        "molmass==2020.6.10",
        "more-itertools==8.4.0",
        "nbconvert==5.6.1",
        "nbformat==5.0.7",
        "networkx==2.4",
        "notebook==6.0.3",
        "numpy==1.19.1",
        "outcome==1.0.1",
        "packaging==20.4",
        "pandas==1.1.0",
        "pandocfilters==1.4.2",
        "parso==0.7.1",
        "patsy==0.5.1",
        "pickleshare==0.7.5",
        "pillow==7.2.0",
        "pluggy==0.13.1",
        "prometheus-client==0.8.0",
        "prompt-toolkit==3.0.5",
        "psims==0.1.31",
        "py==1.9.0",
        "pycparser==2.20",
        "pydoe==0.3.8",
        "pygments==2.6.1",
        "pymzml==2.4.7",
        "pyparsing==2.4.7",
        "pyrsistent==0.16.0",
        "pytest==6.0.1",
        "python-dateutil==2.8.1",
        "pytz==2020.1",
        "pywin32==228; sys_platform == 'win32'",
        "pywinpty==0.5.7; os_name == 'nt'",
        "pyzmq==18.1.1",
        "qtconsole==4.7.5",
        "qtpy==1.9.0",
        "regex==2020.7.14",
        "requests==2.24.0",
        "scikit-learn==0.21.3",
        "scipy==1.5.2",
        "seaborn==0.10.1",
        "send2trash==1.5.0",
        "six==1.15.0",
        "sniffio==1.1.0",
        "sortedcontainers==2.2.2",
        "sqlalchemy==1.3.18",
        "statsmodels==0.11.1",
        "tabulate==0.8.7",
        "terminado==0.8.3",
        "testpath==0.4.4",
        "toml==0.10.1",
        "tornado==6.0.4",
        "tqdm==4.48.0",
        "traitlets==4.3.3",
        "trio==0.16.0",
        "urllib3==1.25.10",
        "wcwidth==0.2.5",
        "webencodings==0.5.1",
        "widgetsnbextension==3.5.1",
        "win32-setctime==1.0.1; sys_platform == 'win32'",
        "xlrd==1.2.0",
        "zipp==3.1.0",
    ],
)
